site_name: django-fast-treenode
repo_url: https://github.com/TimurKady/django-fast-treenode
repo_name: django-fast-treenode
docs_dir: docs

theme:
  name: readthedocs
  palette:
    scheme: slate
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - search.highlight
    - search.share

nav:
  - Home: index.md
  - About Treenode Framework: about.md
  - Installation:
      - Installation & Configuration: installation.md
      - Migration Guide: migration.md
  - Models:
      - Model Inheritance & Extensions: models.md
      - API Reference: api.md
      - Using API: using.md
  - Admin Classes:
      - Working with Admin Classes: admin.md
      - Drag-n-drop: dnd.md
      - Import & Export: import_export.md
  - Advanced:
      - API-First support: apifirst.md
      - Caching: cache.md
      - Customization Guide: customization.md
  - Development:
      - Roadmap: roadmap.md
      

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.emoji
  - admonition

plugins:
  - search
  - mkdocstrings

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TimurKady/django-fast-treenode

