name Run Tests

on
  push
    branches
      - main
  pull_request
    branches
      - main

jobs
  test
    runs-on ubuntu-latest
    steps
      - name Checkout repo
        uses actionscheckout@v3

      - name Setup Python
        uses actionssetup-python@v4
        with
          python-version 3.12

      - name Install dependencies
        run 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name Run tests
        run pytest
